Repository GSG-G10/TechBids, pull requests merged in 2021-12, with the labels that each got.

#43 product details route
  package-lock.json
  server/src/config/data.json
  server/src/controllers/index.js
  server/src/controllers/products/index.js
  server/src/controllers/products/productDetails.js
  server/src/models/product.js
  server/src/routes/index.js
  server/tests/productDetails.test.js
Labels: Awaiting Review

#46 create bid history route
  server/src/controllers/auctions/getAuction.js
  server/src/controllers/auctions/index.js
  server/tests/productHistory.test.js
Labels: Awaiting Review

#51 Nav bar
  client/package-lock.json
  client/public/index.html
  client/public/manifest.json
  client/src/App.tsx
  client/src/Components/Common/NavBar/SearchBar.tsx
  client/src/Components/Common/NavBar/index.tsx
  client/src/images/navLogo.png
  client/src/pages/Bids/index.tsx
  server/src/controllers/index.js
  server/src/controllers/users/index.js
  server/src/controllers/users/logout.js
  server/src/controllers/users/signIn.js
  server/src/routes/index.js
Labels: Awaiting Review, Front-End, Component

#50 12 filter product
  client/package-lock.json
  package-lock.json
  package.json
  server/src/config/data.json
  server/src/controllers/index.js
  server/src/controllers/products/getFilteredProducts.js
  server/src/controllers/products/index.js
  server/src/controllers/validations/filterProductsSchema.js
  server/src/controllers/validations/index.js
  server/src/models/auction.js
  server/src/models/index.js
  server/src/models/product.js
  server/src/routes/index.js
  server/tests/filterProduct.test.js
  server/tests/productDetails.test.js
  server/tests/productHistory.test.js
  server/tests/signUp.test.js
Labels: Awaiting Review

#54 15 header component
  client/package-lock.json
  client/package.json
  client/public/index.html
  client/src/App.css
  client/src/App.tsx
  client/src/Components/Header/index.tsx
  client/src/Components/Header/style.css
  server/src/config/data.json
  server/src/controllers/categories/getTopGategories.js
  server/src/controllers/categories/index.js
  server/src/controllers/index.js
  server/src/controllers/products/getFilteredProducts.js
  server/src/models/product.js
  server/src/routes/index.js
  server/tests/filterProduct.test.js
  server/tests/productDetails.test.js
  server/tests/topCategories.test.js
Labels: Awaiting Review

#37 Side Bar in bids details page
  client/src/App.css
  client/src/App.tsx
  client/src/Components/BidsCategoriesSelect.tsx
  client/src/Components/BidsDetailsPriceBar.tsx
  client/src/Components/BidsStatusCheckBox.tsx
  client/src/Components/Header/index.tsx
  client/src/pages/Bids/index.tsx
  client/src/pages/Bids/style.css
  client/src/pages/style.css
  server/src/controllers/categories/getGategories.js
  server/src/controllers/categories/index.js
  server/src/controllers/index.js
  server/src/routes/index.js
  server/tests/allCategories.test.js
Labels: Awaiting Review, Front-End

#55 Sign up page
  client/src/App.tsx
  client/src/Components/Header/index.tsx
  client/src/Components/Header/style.css
  client/src/Components/SignUpForm/index.tsx
  client/src/context/useAuth.tsx
  client/src/pages/SignUp/index.tsx
  client/src/theme.tsx
  server/src/controllers/users/addUser.js
Labels: Awaiting Review, Front-End, Page

#53 create product details page style
  client/package.json
  client/src/App.tsx
  client/src/Components/Common/Timer/index.tsx
  client/src/Components/HistoryProduct/Style.css
  client/src/Components/HistoryProduct/index.tsx
  client/src/pages/ProductDetails/Style.css
  client/src/pages/ProductDetails/index.tsx
  client/tsconfig.json
  server/src/config/connection.js
  server/src/config/data.json
  server/src/controllers/auctions/getAuction.js
  server/src/controllers/index.js
  server/src/controllers/products/productDetails.js
  server/src/models/index.js
  server/src/routes/index.js
  server/tests/filterProduct.test.js
  server/tests/productDetails.test.js
  server/tests/productHistory.test.js
Labels: Awaiting Review, Front-End

#65 Latest Actions
  client/src/App.tsx
  server/src/controllers/auctions/index.js
  server/src/controllers/auctions/latestAuction.js
  server/src/controllers/index.js
  server/src/routes/index.js
  server/tests/latestAuction.test.js
Labels: Awaiting Review, Back-End, Route

#69 Latest Actions Section
  client/src/App.tsx
  client/src/Components/Common/LastAuction/index.tsx
  client/src/Components/Common/LastAuction/style.css
Labels: Awaiting Review, Front-End

#61 User products
  client/package-lock.json
  client/src/App.tsx
  client/src/Components/Common/NavBar/index.tsx
  client/src/pages/UserProducts/index.tsx
  server/src/config/data.json
  server/src/controllers/categories/getTopGategories.js
  server/src/controllers/index.js
  server/src/controllers/products/getUserProducts.js
  server/src/controllers/products/index.js
  server/src/routes/index.js
  server/tests/allCategories.test.js
  server/tests/latestAuction.test.js
  server/tests/topCategories.test.js
  server/tests/userProducts.test.js
Labels: Awaiting Review, Back-End, Route

#70 User win bids
  client/src/App.tsx
  client/src/pages/UserWinBids/index.tsx
  server/src/controllers/index.js
  server/src/controllers/products/getUserWinBids.js
  server/src/controllers/products/index.js
  server/src/routes/index.js
  server/tests/userWinBids.test.js
Labels: Awaiting Review, Back-End, Route

#63 readme
  README.md
  client/src/App.tsx
Labels: Awaiting Review

#72 Collect the home page
  client/src/App.tsx
  client/src/pages/Home/index.tsx
Labels: Awaiting Review, Front-End

#73 60 bids page
  client/.eslintrc.json
  client/package-lock.json
  client/package.json
  client/src/App.tsx
  client/src/Components/BidsCategoriesSelect.tsx
  client/src/Components/BidsDetailsPriceBar.tsx
  client/src/Components/BidsStatusCheckBox.tsx
  client/src/Components/Common/LastAuction/index.tsx
  client/src/Components/Common/LastAuction/style.css
  client/src/Components/Common/ProductCard/index.tsx
  client/src/Components/Common/ProductCard/style.css
  client/src/Components/Common/Timer/TimerCell.tsx
  client/src/Components/Common/Timer/index.tsx
  client/src/pages/Bids/index.tsx
  client/src/pages/Bids/style.css
  client/src/pages/ProductDetails/Style.css
  package-lock.json
  server/src/config/data.json
  server/src/controllers/products/getFilteredProducts.js
  server/tests/filterProduct.test.js
  server/tests/latestAuction.test.js
  server/tests/productDetails.test.js
Labels: Awaiting Review

#76 Product details page
  client/src/Components/HistoryProduct/Style.css
  client/src/Components/HistoryProduct/index.tsx
  client/src/pages/ProductDetails/Style.css
  client/src/pages/ProductDetails/index.tsx
  client/src/pages/socket.io/index.tsx
  server/src/app.js
  server/src/controllers/auctions/getAuction.js
Labels: Awaiting Review, Front-End

#75 User entered bids
  client/src/App.tsx
  client/src/Components/Common/NavBar/index.tsx
  client/src/pages/Bids/index.tsx
  client/src/pages/UserEnteredBids/index.tsx
  server/src/config/data.json
  server/src/controllers/auctions/getUserEnteredBids.js
  server/src/controllers/auctions/index.js
  server/src/controllers/index.js
  server/src/routes/index.js
  server/tests/productHistory.test.js
  server/tests/userEnteredProducts.test.js
Labels: Awaiting Review, Back-End, Route

#77 Edit style
  client/src/App.tsx
  client/src/Components/Common/NavBar/index.tsx
  client/src/pages/Bids/index.tsx
  client/src/pages/Bids/style.css
  client/src/pages/ProductDetails/Style.css
  client/src/pages/ProductDetails/index.tsx
  client/src/pages/UserEnteredBids/index.tsx
  server/src/config/data.json
  server/src/controllers/auctions/getUserEnteredBids.js
  server/src/controllers/auctions/index.js
  server/src/controllers/index.js
  server/src/routes/index.js
  server/tests/productHistory.test.js
  server/tests/userEnteredProducts.test.js
Labels: Awaiting Review
