Repository GSG-G10/TechBids, pull requests merged in 2021-11, with the labels that each got.

#1 File structure
  .eslintrc.json
  .gitignore
  .vscode/settings.json
  client/.eslintrc.json
  client/.gitignore
  client/README.md
  client/package-lock.json
  client/package.json
  client/public/favicon.ico
  client/public/index.html
  client/public/logo192.png
  client/public/logo512.png
  client/public/manifest.json
  client/public/robots.txt
  client/src/App.css
  client/src/App.tsx
  client/src/index.css
  client/src/index.tsx
  client/src/react-app-env.d.ts
  client/tsconfig.json
  package-lock.json
  package.json
  server/app.js
  server/controllers/auctions/index.js
  server/controllers/categories/index.js
  server/controllers/index.js
  server/controllers/middlewares/index.js
  server/controllers/products/index.js
  server/controllers/users/index.js
  server/controllers/validations/index.js
  server/index.js
  server/models/auction.js
  server/models/category.js
  server/models/product.js
  server/models/user.js
  server/routes/index.js
  server/tests/index.test.js
  server/utils/index.js
Labels: Awaiting Review

#13 Database
  .eslintrc.json
  client/.eslintrc.json
  client/package-lock.json
  client/package.json
  client/src/App.tsx
  client/src/index.tsx
  package-lock.json
  package.json
  server/controllers/middlewares/index.js
  server/controllers/products/index.js
  server/controllers/users/index.js
  server/controllers/validations/index.js
  server/src/app.js
  server/src/config/connection.js
  server/src/config/dbBuild.js
  server/src/controllers/auctions/index.js
  server/src/controllers/categories/index.js
  server/src/controllers/index.js
  server/src/controllers/middlewares/index.js
  server/src/controllers/products/index.js
  server/src/controllers/users/index.js
  server/src/controllers/validations/index.js
  server/src/index.js
  server/src/models/auction.js
  server/src/models/category.js
  server/src/models/index.js
  server/src/models/product.js
  server/src/models/user.js
  server/src/routes/index.js
  server/src/utils/index.js
  server/tests/index.test.js
Labels: Awaiting Review

#22 Convert jwt to Promise
  server/src/utils/index.js
  server/src/utils/signInJwt.js
  server/src/utils/verifyJwt.js
Labels: Awaiting Review, Back-End

#26 Boomify
  server/src/utils/boomify.js
  server/src/utils/index.js
Labels: Awaiting Review, Back-End

#29 Error Function
  server/src/controllers/error/clientError.js
  server/src/controllers/error/index.js
  server/src/controllers/error/serverError.js
  server/src/controllers/index.js
  server/src/routes/index.js
Labels: Awaiting Review, Back-End

#27 Auth context
  client/.eslintrc.json
  client/src/context/useAuth.tsx
  client/src/types.d.ts
Labels: Awaiting Review, Front-End

#31 snack hook and context
  client/package-lock.json
  client/package.json
  client/src/App.tsx
  client/src/context/useSnack.tsx
  client/src/index.tsx
Labels: Awaiting Review, Front-End

#34 2 post signup
  client/package-lock.json
  server/src/config/connection.js
  server/src/config/data.json
  server/src/config/dbBuild.js
  server/src/controllers/index.js
  server/src/controllers/users/addUser.js
  server/src/controllers/users/index.js
  server/src/controllers/validations/index.js
  server/src/controllers/validations/singUpSchema.js
  server/src/models/user.js
  server/src/routes/index.js
  server/tests/index.test.js
Labels: Awaiting Review

#20 Sign In
  .eslintrc.json
  client/package-lock.json
  package-lock.json
  package.json
  server/src/controllers/index.js
  server/src/controllers/users/index.js
  server/src/controllers/users/signIn.js
  server/src/controllers/validations/index.js
  server/src/controllers/validations/signInValidation.js
  server/src/routes/index.js
  server/tests/signIn.test.js
Labels: Awaiting Review, Front-End

#39 fake data
  package-lock.json
  package.json
  server/src/config/data.json
  server/src/config/dbBuild.js
  server/src/models/auction.js
  server/src/models/category.js
  server/src/models/index.js
  server/tests/index.test.js
Labels: Awaiting Review

#38 Sign in page
  client/package-lock.json
  client/package.json
  client/public/Hammer.png
  client/public/index.html
  client/public/logo192.png
  client/public/logo512.png
  client/src/App.tsx
  client/src/Components/SignInForm/index.tsx
  client/src/context/useAuth.tsx
  client/src/images/logo.png
  client/src/index.css
  client/src/pages/SignIn/index.tsx
  client/src/theme.tsx
  package-lock.json
  server/tests/signIn.test.js
Labels: Awaiting Review, Front-End, Page
